# english.py

# Dicionário de traduções de Português para Inglês.
# A chave é a string exata em português, e o valor é a tradução em inglês.

TRANSLATIONS = {
    # --- Títulos de Janelas ---
    "Adicionar Cards com Delimitadores": "Add Cards with Delimiters",
    "Visualizar Todos os Cards": "View All Cards",
    "Gerenciar Mídia (Ctrl+Z para desfazer)": "Manage Media (Ctrl+Z to undo)",
    "Renomear": "Rename",
    "Visualizando: {}": "Previewing: {}",
    "Confirmação": "Confirmation",
    "Erro na Exportação": "Export Error",
    "Selecionar Mídia para {}": "Select Media for {}",
    "Selecionar Mídia": "Select Media",

    # --- Labels e Textos Gerais ---
    "Idioma:": "Language:",
    "Pronto": "Ready",
    "Cards: {}": "Cards: {}",
    "Digite seus cards:": "Enter your cards:",
    "Etiquetas:": "Tags:",
    "Etiquetas (Selecionado)": "Tags (Selected)",
    "Preview:": "Preview:",
    "Decks": "Decks",
    "Modelos ou Tipos de Notas": "Note Types",
    "Mapeamento de Campos": "Field Mapping",
    "Associe cada parte a um campo:": "Map each part to a field:",
    "Parte {} -> Ignorar": "Part {} -> Ignore",
    "Parte {} -> {}": "Part {} -> {}",
    "Midia {}": "Media {}",
    "Delimitadores:": "Delimiters:",
    "Tab": "Tab",
    "Vírgula": "Comma",
    "Ponto e Vírgula": "Semicolon",
    "Dois Pontos": "Colon",
    "Interrogação": "Question Mark",
    "Barra": "Slash",
    "Exclamação": "Exclamation Mark",
    "Pipe": "Pipe",

    # --- Botões ---
    "Adicionar Imagem, Som ou Vídeo": "Add Image, Sound, or Video",
    "Gerenciar Mídia": "Manage Media",
    "Exportar para HTML": "Export to HTML",
    "Visualizar Cards": "View Cards",
    "Mostrar": "Show",
    "Mostrar Etiquetas": "Show Tags",
    "Ocultar Etiquetas": "Hide Tags",
    "Mudar Tema": "Change Theme",
    "Tema Claro": "Light Theme",
    "Tema Escuro": "Dark Theme",
    "📝 Editar em Grade": "📝 Edit in Grid",
    "📄 Editar como Texto": "📄 Edit as Text",
    "Juntar Linhas": "Join Lines",
    "Destaque": "Highlight",
    "Concatenar": "Concatenate",
    "Limpar Tudo": "Clear All",
    "Desfazer": "Undo",
    "Refazer": "Redo",
    "Pesquisar": "Search",
    "Substituir Tudo": "Replace All",
    "Cloze 1 (Ctrl+Shift+D)": "Cloze 1 (Ctrl+Shift+D)",
    "Cloze 2 (Ctrl+Shift+F)": "Cloze 2 (Ctrl+Shift+F)",
    "Remover Cloze": "Remove Cloze",
    "Criar Deck": "Create Deck",
    "Ocultar Decks/Modelos/Delimitadores": "Hide Decks/Models/Delimiters",
    "Mostrar Decks/Modelos/Delimitadores": "Show Decks/Models/Delimiters",
    "Adicionar Cards (Ctrl+R)": "Add Cards (Ctrl+R)",
    "Excluir": "Delete",
    "Visualizar": "Preview",
    "Desfazer (Ctrl+Z)": "Undo (Ctrl+Z)",
    "Tocar": "Play",
    "Pausar": "Pause",
    "Ocultar Lista": "Hide List",
    "Mostrar Lista": "Show List",
    "Aumentar Zoom": "Zoom In",
    "Diminuir Zoom": "Zoom Out",

    # --- Placeholders e Tooltips ---
    "Exportar cards para arquivo HTML": "Export cards to an HTML file",
    "Mostra todos os cards do deck em 'Digite seus cards'": "Shows all cards from the selected deck in the 'Enter your cards' area",
    "Aplicar cor ao texto": "Apply color to text",
    "Aplicar cor de fundo ao texto": "Apply background color to text",
    "Digite seus cards aqui...": "Enter your cards here...",
    "Digite as etiquetas aqui (uma linha por card)...": "Enter tags here (one line per card)...",
    "Alterna entre a edição de texto livre e uma grade estilo planilha.": "Toggles between free text editing and a spreadsheet-style grid.",
    "Juntar todas as linhas (sem atalho)": "Join all lines (no shortcut)",
    "Destacar texto (Ctrl+M)": "Highlight text (Ctrl+M)",
    "Negrito (Ctrl+B)": "Bold (Ctrl+B)",
    "Itálico (Ctrl+I)": "Italic (Ctrl+I)",
    "Sublinhado (Ctrl+U)": "Underline (Ctrl+U)",
    "Concatenar texto (sem atalho)": "Concatenate text (no shortcut)",
    "Limpar todos os campos e configurações": "Clear all fields and settings",
    "Desfazer (Ctrl+Z)": "Undo (Ctrl+Z)",
    "Refazer (Ctrl+Y)": "Redo (Ctrl+Y)",
    "Pesquisar... Ctrl+P": "Search... Ctrl+P",
    "Substituir tudo por... Ctrl+Shift+R": "Replace all with... Ctrl+Shift+R",
    "Adicionar Cloze 1 (Ctrl+Shift+D)": "Add Cloze 1 (Ctrl+Shift+D)",
    "Adicionar Cloze 2 (Ctrl+Shift+F)": "Add Cloze 2 (Ctrl+Shift+F)",
    "Remover Cloze (sem atalho)": "Remove Cloze (no shortcut)",
    "Pesquisar decks...": "Search decks...",
    "Digite o nome do novo deck...": "Enter the name of the new deck...",
    "Pesquisar tipos de notas...": "Search note types...",
    "Adicionar Cards (Ctrl+R)": "Add Cards (Ctrl+R)",

    # --- Checkboxes ---
    "Numerar Tags": "Number Tags",
    "Repetir Tags": "Repeat Tags",

    # --- Mensagens de Status e Avisos ---
    "Salvando...": "Saving...",
    "Salvo": "Saved",
    "Erro ao salvar": "Save Error",
    "A janela principal do Anki não está disponível!": "Anki's main window is not available!",
    "Por favor, selecione uma célula na grade primeiro.": "Please select a cell in the grid first.",
    "Tem certeza de que deseja limpar tudo? Isso não pode ser desfeito.": "Are you sure you want to clear everything? This cannot be undone.",
    "Todos os campos e configurações foram limpos!": "All fields and settings have been cleared!",
    "Selecione um deck e um modelo!": "Please select a deck and a note type!",
    "Digite algum conteúdo!": "Please enter some content!",
    "{} cards adicionados com sucesso!": "{} cards added successfully!",
    "Selecione um deck primeiro!": "Please select a deck first!",
    "Deck '{}' não encontrado!": "Deck '{}' not found!",
    "Nenhum card encontrado no deck '{}'!": "No cards found in deck '{}'!",
    "Erro ao salvar estado antes de 'Mostrar': {}": "Error saving state before 'Show': {}",
    "Nenhum estado anterior salvo encontrado!": "No previous saved state found!",
    "Por favor, insira um texto para pesquisar.": "Please enter text to search for.",
    "Texto '{}' não encontrado.": "Text '{}' not found.",
    "Todas as ocorrências de '{}' foram substituídas por '{}'.": "All occurrences of '{}' have been replaced with '{}'.",
    "Todas as ocorrências de '{}' foram removidas.": "All occurrences of '{}' have been removed.",
    "Por favor, insira um nome para o deck!": "Please enter a name for the deck!",
    "Erro ao criar o deck: {}": "Error creating deck: {}",
    "Por favor, selecione uma palavra para adicionar o cloze.": "Please select a word to add the cloze to.",
    "Erro ao carregar configurações: {}": "Error loading settings: {}",
    "Nenhum arquivo de mídia foi adicionado ou referenciado no texto!": "No media files have been added or referenced in the text!",
    "Ocorreu um erro durante a exportação: {}": "An error occurred during export: {}",
    "Nenhum conteúdo para exibir.": "No content to display.",
    "Linha vazia.": "Empty line.",
    "Selecione um deck e um tipo de nota para visualizar.": "Select a deck and a note type to preview.",
    "Erro na pré-visualização:": "Error in preview:",
    "Colar HTML sem Tag e sem Formatação": "Paste HTML without Tags and Formatting",
    "Colar com Tags HTML": "Paste with HTML Tags",
    "Colar do Excel com Ponto e Vírgula": "Paste from Excel with Semicolon",
    "Colar do Word": "Paste from Word",
    "Nenhuma imagem, texto ou HTML encontrado na área de transferência.": "No image, text, or HTML found on the clipboard.",
    "Nenhum texto encontrado na área de transferência para colar como Excel.": "No text found on the clipboard to paste as Excel.",
    "Nenhum texto encontrado na área de transferência para colar como Word.": "No text found on the clipboard to paste as Word.",
    "Nenhum texto ou HTML encontrado na área de transferência.": "No text or HTML found on the clipboard.",
    "🖼️ Adicionar Imagem/Mídia...": "🖼️ Add Image/Media...",

    # --- Strings de VisualizarCards ---
    "Renderizando pré-visualização dos cards...": "Rendering card previews...",
    "Erro ao renderizar card {}:<br><pre>{}</pre>": "Error rendering card {}:<br><pre>{}</pre>",
    "Digite conteúdo para visualizar!": "Enter content to preview!",
    "Selecione um tipo de nota para visualizar!": "Select a note type to preview!",
    "Nenhum card válido para visualizar!": "No valid cards to preview!",

    # --- Strings de MediaManager ---
    "Selecione um arquivo para excluir!": "Select a file to delete!",
    "Arquivo '{}' excluído!": "File '{}' deleted!",
    "Erro ao excluir: {}": "Error deleting: {}",
    "Arquivo '{}' não encontrado!": "File '{}' not found!",
    "Selecione um arquivo para renomear!": "Select a file to rename!",
    "Novo nome:": "New name:",
    "O nome '{}' já existe!": "The name '{}' already exists!",
    "Renomeado para '{}'!": "Renamed to '{}'!",
    "Erro ao renomear: {}": "Error renaming: {}",
    "Nada para desfazer!": "Nothing to undo!",
    "Arquivo '{}' restaurado!": "File '{}' restored!",
    "Erro ao desfazer: {}": "Error undoing: {}",
    "Renomeação revertida!": "Rename reverted!",
    "Selecione um arquivo para visualizar!": "Select a file to preview!",
    "Tipo de arquivo não suportado: {}": "Unsupported file type: {}",
    "Não foi possível carregar a imagem!": "Could not load the image!",
    "Recursos de multimídia (PyQt6.QtMultimedia) não estão instalados.": "Multimedia features (PyQt6.QtMultimedia) are not installed.",

    # --- Strings de ExportHTML ---
    "Cards Exportados": "Exported Cards",
    "Frente": "Front",
    "Verso": "Back",
    "Renderizando e processando cards...": "Rendering and processing cards...",
    "Por favor, selecione um Tipo de Nota para exportar.": "Please select a Note Type to export.",
    "Não há conteúdo para exportar.": "There is no content to export.",
}